# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Increment the build number"
  lane :increment_build do
    increment_build_number 
    git_commit(path: "./version.txt", message: "Version Bump")
  end
end
